### ISSUE TITLE
[BUG] OneHotEncoderTransform got an unexpected keyword argument 'sparse'

### ISSUE THREAD

**Issue by Sm1Ling** [etna-team/etna#497]
### 🐛 Bug Report

It is told that `etna` would work with sklearn version up to 2.0.0

However, I got scikit-learn==1.5.2
OneHotEncoder in sklearn has argument `sparse_output` instead of `sparse` (since version 1.2)

Either dependency version should be restricted, or code should be updated

### Expected behavior

OneHotEncoderTransform should return transformed data matrix

### How To Reproduce

pip install sklearn==1.5.2 
pip install etna==2.9.0
```
ohe = OneHotEncoderTransform(
    in_column="categorical_columns",
    out_column="OneHot",
    return_type="numeric"
)
```

get
```
    [216](.../etna/transforms/encoders/categorical.py:216) self.out_column = out_column
    [217](.../etna/transforms/encoders/categorical.py:217) self.return_type = ReturnType(return_type)
--> [218](.../etna/transforms/encoders/categorical.py:218) self.ohe = preprocessing.OneHotEncoder(handle_unknown="ignore", sparse=False, dtype=int)
    [219](.../etna/transforms/encoders/categorical.py:219) self.in_column_regressor: Optional[bool] = None

TypeError: OneHotEncoder.__init__() got an unexpected keyword argument 'sparse'
```

### Environment

python==3.10.11
OS == windows 10

### Checklist

- [X] Bug appears at the latest library version

**Comment by d-a-bunin** [comment]
Thanks for the issue! We'll look into it.
It isn't really a good thing that `scikit-learn` just renamed the name of the parameter, technically, it is a breaking change.

**Comment by egoriyaa** [comment]
`sparse` parameter was completely removed in version 1.4. Also versions greater then 1.4 do not support python3.8. Be careful, we can't update `scikit-learn` version in our current major version.
